spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #localhost
#    url: jdbc:postgresql://db_backend:5432/marketplace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

app:
  cors:
    allowed-origins: http://localhost:3000